In [ ]:
#Sales_Fact Table
CREATE TABLE IF NOT EXISTS DW_SALES_FACT (
    TRANSACTION_ID SERIAL NOT NULL,
    SALES_ID INT NOT NULL,
    DATE_OF_SALE TIMESTAMP,
    COUNTRY_OF_SALE varchar(255),
    CUSTOMER_CURRENCY varchar(255),
    CUSTOMER_SHARE NUMERIC,
    DELIVARY_COST NUMERIC,
    DISCOUNT NUMERIC,
    EBOOKS_SHARE NUMERIC,
    FINAL_PRICE NUMERIC,
    NET_UNITS INT,
    QUANTITY_OF_SALE INT,
    STORE_PRICE NUMERIC,
    UNITS_RETURNED INT,
    DISTRIBUTION_ORDERINFO_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    STORE_ID INT NOT NULL,
    company_name_id INT,
    FORMAT varchar(45),
    MASTER_CUSTOMER_ID INT,
    FORMAT_ID INT,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (TRANSACTION_ID),
    FOREIGN KEY (DISTRIBUTION_ORDERINFO_ID)
      REFERENCES DW_Distribution_Order_Info_DIM (DISTRIBUTION_ORDERINFO_ID),
    FOREIGN KEY (MASTER_CUSTOMER_ID)
      REFERENCES DW_MASTER_CUSTOMER_DIM (MASTER_CUSTOMER_ID),
    FOREIGN KEY (STORE_ID)
      REFERENCES DW_STORES_DIM (STORE_ID),
    FOREIGN KEY (company_name_id)
      REFERENCES dw_company_name_dim (company_name_id),
    FOREIGN KEY (FORMAT_ID)
      REFERENCES DW_FORMAT_DIM (FORMAT_ID)
);


#Customer_DIM Table **
CREATE TABLE IF NOT EXISTS DW_MASTER_CUSTOMER_DIM (
    MASTER_CUSTOMER_ID SERIAL NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    DATE_CREATED TIMESTAMP,
    ADDRESS_LINE1 VARCHAR(255),
    ADDRESS_LINE2 VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    COUNTRY VARCHAR(255),
    ZIP VARCHAR(255),
    PHONE VARCHAR(255),
    FAX VARCHAR(255),
    EMAIL_ADDRESS VARCHAR(255),
    USER_NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    DEACTIVATED INT,
    ROLE_ID INT,
    IS_PUBLISHER INT,
    WEBSITE VARCHAR(255),
    IS_PARTNER INT,
    LEAD_OWNER INT,
    LEAD_SOURCE VARCHAR(255),
    ORDER_TYPE VARCHAR(255),
    CREATED_DATE TIMESTAMP default current_timestamp,
    UPDATED_DATE TIMESTAMP default current_timestamp,
    PRIMARY KEY (MASTER_CUSTOMER_ID)
);

#Distribution_Order_Info_DIM Table 
CREATE TABLE IF NOT EXISTS DW_Distribution_Order_Info_DIM (
    Distribution_OrderInfo_ID INT NOT NULL,
    ISBN VARCHAR(255) NOT NULL,
    ARCHIVED VARCHAR(255),
    EBOOK VARCHAR(255),
    LIST_PRICE VARCHAR(255) NOT NULL,
    ORDER_STATUS VARCHAR(255),
    ORDER_STATUS_DATE VARCHAR(255),
    TITLE VARCHAR(255),
    DISTRIBUTION_ORDER_INSTORES_ID INT,
    DISTRIBUTION_METADATA_ID INT,
    CUSTOMER_ID INT,
    ORDER_DATE TIMESTAMP,
    CCID VARCHAR(255),
    FORMAT VARCHAR(255),
    UPDATED_STATUS INT,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (Distribution_OrderInfo_ID)
);

#STORES_DIM Table
CREATE TABLE IF NOT EXISTS DW_STORES_DIM (
     STORE_ID INT NOT NULL,
     STORE_NAME VARCHAR(255),
     STORE_ROYALTY VARCHAR(255),
     CREATED_DATE TIMESTAMP,
     UPDATED_DATE TIMESTAMP,
     PRIMARY KEY (STORE_ID)
);

#FORMAT_DIM Table
CREATE TABLE IF NOT EXISTS DW_FORMAT_DIM (
     FORMAT_ID SERIAL NOT NULL,
     FORMAT_TYPE VARCHAR(45),
     CREATED_DATE TIMESTAMP,
     UPDATED_DATE TIMESTAMP,
     PRIMARY KEY (FORMAT_ID)
);

#LOG_DIM Table
CREATE TABLE IF NOT EXISTS LOG_DIM (
    Log_ID SERIAL NOT NULL,
    Run_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Phase VARCHAR(5),
    SOURCE_TABLE_Name VARCHAR(100),
    TARGET_Table_Name VARCHAR(100),
    Total_Records_Source_Table NUMERIC,
    Total_Records_Target_Table NUMERIC,
    New_Records_Source Numeric,
    New_Records_Target Numeric,
    STATUS VARCHAR(10),
    REMARKS VARCHAR(225),
    EXECUTION_TIME VARCHAR(50),
    PRIMARY KEY (LOG_ID)
);

#DATE_DIM Table
CREATE TABLE IF NOT EXISTS DW_DATE_DIM (
     DATE_ID SERIAL NOT NULL,
     YEAR INT,
     MONTH VARCHAR(255),
     DAY VARCHAR(255),
     CREATED_DATE TIMESTAMP,
     UPDATED_DATE TIMESTAMP,
     PRIMARY KEY (DATE_ID)
);


#dw_source_dim table
CREATE TABLE IF NOT EXISTS dw_source_dim (
     source_id SERIAL NOT NULL,
     Source_table varchar(255),
     CREATED_DATE TIMESTAMP,
     UPDATED_DATE TIMESTAMP,
     PRIMARY KEY (ref_ID)
);

#Ref_source Table
CREATE TABLE IF NOT EXISTS dw_ref_source_dim (
     s_ref_ID SERIAL NOT NULL,
     MASTER_CUSTOMER_ID INT,
     source_id INT,
     customer_id INT,
     CREATED_DATE TIMESTAMP,
     UPDATED_DATE TIMESTAMP,
     PRIMARY KEY (ref_ID)
);

#Master Customer test table
CREATE TABLE IF NOT EXISTS MASTER_CUSTOMER_test (
    MASTER_CUSTOMER_ID SERIAL NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    DATE_CREATED TIMESTAMP,
    ADDRESS_LINE1 VARCHAR(255),
    ADDRESS_LINE2 VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    COUNTRY VARCHAR(255),
    ZIP VARCHAR(255),
    PHONE VARCHAR(255),
    FAX VARCHAR(255),
    EMAIL_ADDRESS VARCHAR(255),
    USER_NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    DEACTIVATED INT,
    ROLE_ID INT,
    IS_PUBLISHER INT,
    WEBSITE VARCHAR(255),
    IS_PARTNER INT,
    LEAD_OWNER INT,
    LEAD_SOURCE VARCHAR(255),
    ORDER_TYPE VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (MASTER_CUSTOMER_ID)
);

"""insert into mct (customer_id,first_name,last_name,date_created,address_line1,city,state,zip,phone,email_address) 
values (1,'Mahi','Chall','01/12/2012','1807 Grove Ave','schaumburg','il','60193','','mc@gmail.com'),
 (2,'M','Chall','12-22-2017','1807 Grove Ave','schaumburg','il','60195','+1 6303478097','mc@gmail.com'),
 (3,'Mahi','Chall','07-27-2018',' ','','','','6303478097','mc@gmail.com'),
 (9,'M','Chal','08-20-2018',' ','','','60193','6303478097','mc@gmail.com'),
 (4,'Sushank','Abb','08-27-2016','109 Heather Court','Arlington Heights','il','60197','','sa@gmail.com'),
 (5,'Sush','A','07-27-2017','1O9 Heather Court','Arlington Heights','il','60197','6303652713','sa@gmail.com'),
 (10,'Sush','Abb','01-27-2018','','Rolling Meadows','','','6303652737','sa@gmail.com'),
 (6,'Mimi','Ikonn','07-25-2018','165 Downer''s Grove','','London','50032','','MI@gmail.com'),
 (7,'Alexa','','07-27-2019','505 Lilly St','Lailatown','Ar','33626','5432713500','alexalove@gmail.com'),
 (8,'Alexa','','07-28-2019','120 Lake St','Ramenvilla','WA','33626','5432713500','alexalove@gmail.com'),
 (11,'Alexa','Ik','01-02-2020','120 Lake St','','','0052-33652','','alexalove@gmail.com'),
 (12,'Lee','Nightingale','07-26-2018','1234 5th St.','LowDo Denver','Co','25005','6302257281','nightingaleinvestigations@yahoo.com'),
 (13,'Liam','Nightingale','09-05-2020','1234 5th St.','Denver','Colorado','5020-25005','+1 6302257281','nightingaleinvestigations@yahoo.com'),
 (14,'Lee','Nightingale','09-05-2020','','Denver','Colorado','','','nightingaleinvestigations@yahoo.com')
"""



#Ref_company_name Table
CREATE TABLE IF NOT EXISTS dw_company_name_dim (
     company_name_ID SERIAL NOT NULL,
     MASTER_CUSTOMER_ID INT,
     first_name varchar(255),
     last_name varchar(255),
     company_name varchar(255),
     CREATED_DATE TIMESTAMP default current_timestamp,
     UPDATED_DATE TIMESTAMP default current_timestamp,
     PRIMARY KEY (company_name_ID)
);